server:
  port: 9090

spring:
  data:
    mongodb:
      #host: ds163182.mlab.com
      #port: 63182
      #username: Bhargo_RO
      #password:
      #set while building the image using docker
      uri: mongodb://Bhargo_RO:M0ngo#2000@ds163182.mlab.com:63182/mongoml
      database: mongoml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true