server:
  port: 9090

spring:
  data:
    mongodb:
      #host: ds163182.mlab.com
      #port: 63182
      #username: Bhargo_RO
      #password:
      #set while building the image using docker
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@ds163182.mlab.com:63182/mongoml
      database: mongoml